services:
  mariadb:
    image: mariadb:10.9
    ports:
      - 23456:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test
      MYSQL_DATABASE: test
    restart: on-failure

volumes:
  mariadb_data:
